name: Build and Test - Foxy

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Test on ROS2 Foxy
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2.3.4

      - name: Building and testing on ROS2 Foxy
        uses: ichiro-its/ros2-ci@v1.0.0
        with:
          apt-packages: ros-foxy-dynamixel-sdk
          ros2-distro: foxy
