name: Build and Test - Humble

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Test on ROS2 Humble
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2.3.4

      - name: Building and testing on ROS2 Humble
        uses: ichiro-its/ros2-ci@v1.0.0
        with:
          apt-packages: ros-humble-dynamixel-sdk libboost-all-dev qtbase5-dev qt5-qmake
          ros2-distro: humble
